language: java

jdk:
  - oraclejdk8

#notifications:
#  email:
#    recipients:
#      - one@example.com
#      - other@example.com
#    on_success: [always|never|change] # default: change
#    on_failure: [always|never|change] # default: always

