language: java

jdk:
  - oraclejdk8
  
#before_install:
#  cd carpetaDondeEstaElPOM #solo si no tienen el pom en el raíz del repositorio


#si usamos codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)

#notifications:
#  email:
#    recipients:
#      - one@example.com
#      - other@example.com
#    on_success: [always|never|change] # default: change
#    on_failure: [always|never|change] # default: always

