language: java

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - canofedericomartin@gmail.com
      - gastonprietoutn@gmail.com
    #on_success: [always|never|change] # default: change
    on_failure: always # default: always
